In [1]:
import pandas as pd
import numpy as np

In [2]:
s={'Temperature':[35,33,30,28,27],'Ie_cream_sales':[5000,4000,3000,2000,500]}
print(s)

{'Temperature': [35, 33, 30, 28, 27], 'Ie_cream_sales': [5000, 4000, 3000, 2000, 500]}


In [3]:
df=pd.DataFrame(s)
df

,Temperature,Ie_cream_sales
0,35,5000
1,33,4000
2,30,3000
3,28,2000
4,27,500


In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
x=df['Temperature']  
y=df['Ie_cream_sales'] 

In [6]:
mx=np.mean(x)     #mean of x
mx

np.float64(30.6)

In [7]:
my=np.mean(y)    #mean of y
my

np.float64(2900.0)

In [8]:
vx=np.var(x)    #varience of x
vx

np.float64(9.040000000000001)

In [9]:
vy=np.var(y)    #varience of y
vy

np.float64(2440000.0)

In [10]:
sx=np.std(x)    #standard deviation of x

In [11]:
sy=np.std(y)    #standard deviation of y

In [12]:
cvx=sx/mx       #covarience of x
print(cvx*100)


9.825683907433273


In [13]:
cvy=sy/my       #covarience of y
print(cvy*100)

53.86379086832176


In [14]:
cv=np.cov(x,y)    #covarience of x,y
cv

array([[1.13e+01, 5.70e+03],
       [5.70e+03, 3.05e+06]])

In [15]:
m=cv/vx        #slope
m

array([[1.25000000e+00, 6.30530973e+02],
       [6.30530973e+02, 3.37389381e+05]])

In [16]:
c=my-m*mx   #intercept
c

array([[ 2.86175000e+03, -1.63942478e+04],
       [-1.63942478e+04, -1.03212150e+07]])

In [17]:
yp=m*mx+c   #predicted value
yp

array([[2900., 2900.],
       [2900., 2900.]])