In [72]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [73]:
df=pd.read_excel('standardscaler1.xlsx')

In [74]:
df

,Feature1,Feature2,Feature3,Target
0,7,506815,78179.054805,147107.322662
1,4,293822,70538.588873,127684.231772
2,8,77218,44636.920014,87982.249559
3,5,588518,86421.631346,166046.587018
4,7,771044,55814.069145,101011.603738
...,...,...,...,...
995,8,318348,38587.511702,68752.511537
996,1,183958,79172.046754,144130.196824
997,9,990156,59598.924619,103252.136934
998,7,278707,10126.081336,22002.231220


In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Feature1  1000 non-null   int64  
 1   Feature2  1000 non-null   int64  
 2   Feature3  1000 non-null   float64
 3   Target    1000 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 31.4 KB


In [76]:
x=df.drop('Target',axis=1)
y=df['Target']

In [77]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [78]:
model=LinearRegression()

In [79]:
model.fit(xtrain,ytrain)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [80]:
train_score=model.score(xtrain,ytrain)
train_score

0.9902808869604561

In [81]:
test_score=model.score(xtest,ytest)
test_score

0.9902822563064015

In [82]:
model.coef_

array([-1.90917070e+01,  2.55230384e-04,  1.79990677e+00])

**with Using StandardScalar()**

In [83]:
scaler=StandardScaler()

In [84]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled


array([[ 0.04029928,  1.20894202,  1.30817812],
       [ 1.59400657,  0.88435119,  0.91114696],
       [ 0.4287261 , -1.24831658,  0.53753872],
       [ 1.20557975,  0.90052814,  0.00295259],
       [-0.73655436, -0.75826634,  0.99043722],
       [-1.12498118,  1.20470035, -0.74078814],
       [-1.12498118, -0.29065208, -0.54749276],
       [ 1.59400657, -0.1559706 ,  0.57691668],
       [ 1.59400657, -1.55783743,  1.56383811],
       [ 0.4287261 , -1.78565622,  1.02825118],
       [-0.73655436, -1.68545292,  0.12557919],
       [ 1.20557975,  1.42494622, -0.69080137],
       [-1.513408  , -1.06572153,  0.16861156],
       [-1.513408  ,  0.63978299, -0.93518994],
       [-0.73655436,  0.62916159,  0.87745526],
       [ 0.04029928, -0.50244566, -0.75674424],
       [-1.513408  ,  0.80383197, -0.63243624],
       [ 0.04029928,  1.46721114,  0.43662534],
       [ 0.4287261 , -0.462474  , -1.61086096],
       [-1.12498118, -1.0698356 ,  0.67584916],
       [ 1.59400657, -1.23433978,  0.821

In [85]:
model.fit(xtrain_scaled,ytrain)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [86]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [87]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064015

In [88]:
model.coef_

array([-4.91513611e+01,  7.40118263e+01,  5.19891719e+04])

**Using Robust scaler**

In [89]:
from sklearn.preprocessing import RobustScaler,MinMaxScaler

In [90]:
scaler=RobustScaler()

In [91]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled

array([[ 0.        ,  0.69172071,  0.71254131],
       [ 1.        ,  0.50357551,  0.48955076],
       [ 0.25      , -0.73259994,  0.27971557],
       [ 0.75      ,  0.51295229, -0.02053205],
       [-0.5       , -0.44854816,  0.53408373],
       [-0.75      ,  0.68926208, -0.43825029],
       [-0.75      , -0.17750113, -0.32968691],
       [ 1.        , -0.09943461,  0.301832  ],
       [ 1.        , -0.91201001,  0.85613146],
       [ 0.25      , -1.04406246,  0.55532175],
       [-0.5       , -0.98598081,  0.04834057],
       [ 0.75      ,  0.81692497, -0.41017547],
       [-1.        , -0.62676089,  0.07250948],
       [-1.        ,  0.36181447, -0.54743508],
       [-0.5       ,  0.3556579 ,  0.47062798],
       [ 0.        , -0.30026475, -0.44721196],
       [-1.        ,  0.4569035 , -0.37739499],
       [ 0.        ,  0.84142333,  0.22303807],
       [ 0.25      , -0.27709566, -0.92692232],
       [-0.75      , -0.62914557,  0.35739693],
       [ 1.        , -0.72449845,  0.439

In [92]:
model.fit(xtrain_scaled,ytrain)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [93]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [94]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064014

In [95]:
model.coef_

array([-7.63668279e+01,  1.27686274e+02,  9.25658986e+04])

**Using MinMaxScaler**

In [96]:
scaler=MinMaxScaler()

In [97]:
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)
xtrain_scaled
xtest_scaled

array([[ 5.00000000e-01,  8.72750347e-01,  8.76783323e-01],
       [ 1.00000000e+00,  7.77944643e-01,  7.61728835e-01],
       [ 6.25000000e-01,  1.55040189e-01,  6.53462006e-01],
       [ 8.75000000e-01,  7.82669567e-01,  4.98545866e-01],
       [ 2.50000000e-01,  2.98172881e-01,  7.84706126e-01],
       [ 1.25000000e-01,  8.71511452e-01,  2.83019437e-01],
       [ 1.25000000e-01,  4.34752523e-01,  3.39033934e-01],
       [ 1.00000000e+00,  4.74089966e-01,  6.64873228e-01],
       [ 1.00000000e+00,  6.46360871e-02,  9.50870278e-01],
       [ 6.25000000e-01, -1.90467557e-03,  7.95664121e-01],
       [ 2.50000000e-01,  2.73624625e-02,  5.34081468e-01],
       [ 8.75000000e-01,  9.35840334e-01,  2.97504953e-01],
       [ 0.00000000e+00,  2.08372112e-01,  5.46551692e-01],
       [ 0.00000000e+00,  7.06511754e-01,  2.26684312e-01],
       [ 2.50000000e-01,  7.03409480e-01,  7.51965416e-01],
       [ 5.00000000e-01,  3.72892367e-01,  2.78395563e-01],
       [ 0.00000000e+00,  7.54426784e-01

In [98]:
model.fit(xtrain_scaled,ytrain)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [99]:
train_score=model.score(xtrain_scaled,ytrain)
train_score

0.9902808869604561

In [100]:
test_score=model.score(xtest_scaled,ytest)
test_score

0.9902822563064015

In [101]:
model.coef_

array([-1.52733656e+02,  2.53397830e+02,  1.79404745e+05])

* array([-1.90917070e+01,  2.55230384e-04,  1.79990677e+00])--->without Standard Scaler
* array([-4.91513611e+01,  7.40118263e+01,  5.19891719e+04])---->with standard Scaler
* array([-7.63668279e+01,  1.27686274e+02,  9.25658986e+04])---->Robust Scaler
* array([-1.52733656e+02,  2.53397830e+02,  1.79404745e+05])----->Minmax Scaler

**using Label encoder**

In [102]:
from sklearn.preprocessing import LabelEncoder

In [103]:
df=pd.DataFrame({'color':['Red','Blue','Green','Red','Blue'],'level':['low','high','medium','low','high'],'size':['small','large','medium','large','small'],'city':['newyork','washington','newyork','delhi','washington'],'purchased':['yes','no','no','yes','yes']})

In [104]:
label_encoder=LabelEncoder()

In [105]:
label_encoder.fit(df['color'])

LabelEncoder()

In [106]:
label_encoder.fit_transform(['Red'])

array([0])

In [107]:
label_encoder.transform(['Red'])

array([0])

In [108]:
'''label_encoder.transform(['Redd'])
ValueError:(y contains previously unseen labels: 'Redd')'''

"label_encoder.transform(['Redd'])\nValueError:(y contains previously unseen labels: 'Redd')"

In [109]:
'''label_encoder.transform([['Red','Red']])
ValueError: y should be a 1d array, got an array of shape (1, 2) instead.'''

"label_encoder.transform([['Red','Red']])\nValueError: y should be a 1d array, got an array of shape (1, 2) instead."

**Using One hot encoder**

In [110]:
from sklearn.preprocessing import OneHotEncoder

In [111]:
one_hot_encoder=OneHotEncoder()

In [112]:
one_hot_encoder.fit_transform(df[['size']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (5, 3)>

In [113]:
'''one_hot_encoder.fit_transform(df['size'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.'''

"one_hot_encoder.fit_transform(df['size'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead."

In [114]:
one_hot_encoder.fit(df[['size']])   #it accepts 2D

,categories,'auto'
,drop,None
,sparse_output,True
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,min_frequency,None
,max_categories,None
,feature_name_combiner,'concat'


In [115]:
res=one_hot_encoder.fit_transform(df[['color','city']])
res

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (5, 6)>

In [116]:
res_cols=one_hot_encoder.get_feature_names_out()

In [117]:
res=res.toarray()


In [118]:
pd.DataFrame(res,columns=res_cols)

,color_Blue,color_Green,color_Red,city_delhi,city_newyork,city_washington
0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0


In [119]:
one_hot_encoder=OneHotEncoder(sparse_output=False,dtype='int')

In [120]:
res=one_hot_encoder.fit_transform(df[['color','city']])

In [121]:
one_hot_encoder.fit(df[['color','city']])

,categories,'auto'
,drop,None
,sparse_output,False
,dtype,'int'
,handle_unknown,'error'
,min_frequency,None
,max_categories,None
,feature_name_combiner,'concat'


In [122]:
'''one_hot_encoder.transform(df[['color']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- city'''

"one_hot_encoder.transform(df[['color']])\nValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- city"

In [123]:
one_hot_encoder.fit_transform(df[['color','city']])

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 1]])

In [124]:
'''one_hot_encoder.transform([['Red']])
ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.'''

"one_hot_encoder.transform([['Red']])\nValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input."

In [125]:
one_hot_encoder.transform([['Red','newyork']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0, 0, 1, 0, 1, 0]])

In [126]:
'''one_hot_encoder.transform([['Redd','newyork']])
ValueError: Found unknown categories ['Redd'] in column 0 during transform'''

"one_hot_encoder.transform([['Redd','newyork']])\nValueError: Found unknown categories ['Redd'] in column 0 during transform"

In [127]:
'''one_hot_encoder.transform([['Red','Red']])
ValueError: Found unknown categories ['Red'] in column 1 during transform'''


"one_hot_encoder.transform([['Red','Red']])\nValueError: Found unknown categories ['Red'] in column 1 during transform"

In [128]:
one_hot_encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [129]:
one_hot_encoder.fit_transform(df[['color']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [130]:
one_hot_encoder.transform([['Red'],['Redd']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.],
       [0., 0., 0.]])

In [131]:
one_hot_encoder.transform([['Redd']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0.]])

**Ordinal encoder**

In [132]:
from sklearn.preprocessing import  OrdinalEncoder

In [133]:
ordinal_encoder=OrdinalEncoder()

In [134]:
df

,color,level,size,city,purchased
0,Red,low,small,newyork,yes
1,Blue,high,large,washington,no
2,Green,medium,medium,newyork,no
3,Red,low,large,delhi,yes
4,Blue,high,small,washington,yes


In [135]:
OrdinalEncoder(categories=[['Red','Blue','Green'],['low','high','medium'],['small','large','medium'],['newyork','washington','delhi'],['yes','no']])

,categories,"[['Red', 'Blue', ...], ['low', 'high', ...], ...]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [136]:
'''ordinal_encoder=OrdinalEncoder(categories=['Red','Blue','Green'])
ordinal_encoder.fit_transform(df['color'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.'''

"ordinal_encoder=OrdinalEncoder(categories=['Red','Blue','Green'])\nordinal_encoder.fit_transform(df['color'])\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead."

In [137]:
'''ordinal_encoder=OrdinalEncoder(categories=[['low','high','medium'],['Red','Blue','Green'],['newyork','washington','delhi'],['yes','no'],['small','large','medium']])
ordinal_encoder.fit_transform(df)
ValueError: Found unknown categories ['Blue', 'Red', 'Green'] in column 0 during fit'''

"ordinal_encoder=OrdinalEncoder(categories=[['low','high','medium'],['Red','Blue','Green'],['newyork','washington','delhi'],['yes','no'],['small','large','medium']])\nordinal_encoder.fit_transform(df)\nValueError: Found unknown categories ['Blue', 'Red', 'Green'] in column 0 during fit"

In [138]:
ordinal_encoder.fit_transform(df)

array([[2., 1., 2., 1., 1.],
       [0., 0., 0., 2., 0.],
       [1., 2., 1., 1., 0.],
       [2., 1., 0., 0., 1.],
       [0., 0., 2., 2., 1.]])

In [139]:
'''ordinal_encoder.transform([['Red']])
ValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input'''

"ordinal_encoder.transform([['Red']])\nValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input"

**how to handle unknown values**

In [140]:
'''ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value")
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])
TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.'''

'ordinal_encoder=OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value")\nvalues=ordinal_encoder.fit_transform(df[[\'color\']])\nordinal_encoder.transform([[\'orange\']])\nTypeError: unknown_value should be an integer or np.nan when handle_unknown is \'use_encoded_value\', got None.'

In [141]:
'''ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",unknown_value=0)
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])
ValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'''

'ordinal_encoder=OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value",unknown_value=0)\nvalues=ordinal_encoder.fit_transform(df[[\'color\']])\nordinal_encoder.transform([[\'orange\']])\nValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.'

In [142]:
ordinal_encoder=OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",unknown_value=-1)
values=ordinal_encoder.fit_transform(df[['color']])
ordinal_encoder.transform([['orange']])

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.]])